### ISSUE TITLE
Use public keys instead of passwords

### ISSUE THREAD

**Issue by MCOfficer** [laurent-clouet/sheepit-client#151]
as discussed in #27 , the client stores it's credentials in plaintext, which is an absolute no-go from a security point of view. While encrypting everything is one solution, it's also pretty complex. The best/safest way is to use a public key, however most Users are seemingly unaware that these keys exist/what to do with them.

To prevent people from storing their passwords in plaintext on potentially foreign computers, the client should 
1.  accept public keys ONLY (not sure if there is a good way to distinguish a public key from a password with equal length), or
2. point the users in the right direction and inform them what's happening (for example rename the "password" field to "public key").

**Comment by L00Cyph3r** [comment]
Maybe the easiest solution is to let the client create a public key upon the first login.
The key can than be stored anywhere, since the only thing someone can do with a key is render for you (more points!)

I think this is the smallest (no) step for the user, since the regular password is only necessary upon installation.

**Comment by laurent-clouet** [comment]
I choose the solution where on login a public key is giving to the renderer and stored as a password.
It's been pushed, the 'official' release should be this week with 5.1672.3030
