### ISSUE TITLE
How is blender installed?

### ISSUE THREAD

**Issue by TheGreatRambler** [laurent-clouet/sheepit-client#156]
I am trying to make a port for Raspberry Pi (or ARM in general) [here](https://github.com/TheGreatRambler/sheepit-client). What part of the code installs blender because I believe that is the problem, it installs the wrong blender.

**Comment by laurent-clouet** [comment]
Blender is downloaded from the server so you will not be able to support arm.
If you look at the RaspberryPi thread ( https://github.com/laurent-clouet/sheepit-client/issues/66 ) you can see a patch i made to test blender.

To be honest, arm will not added because:
 * there is not enough power on the raspberryPi to be really usefull
 * there is not enough user to be worth the time spent on it
 * there is no official blender build (i.e. from the blender foundation for arm

**Comment by TheGreatRambler** [comment]
I have read that thread many times. I checked that patch and I changed the [linux file](https://github.com/TheGreatRambler/sheepit-client/blob/master/src/com/sheepit/client/os/Linux.java).

I have a version of blender on my raspi (2.78), installed by `sudo apt-get install blender`, so I believe if there is a separate way of downloading the binary (by `sudo apt-get`) you could get a blender binary. It worked for me. In fact, I already made a web console for rendering a video on the raspi, and it rendered fine.

I agree with the third comment down on that thread, that it would be helpful if I could use the raspi because it's always on, even if it isn't very powerful.

So, I guess what I am asking is which java file downloads the binary from the server, so I can edit that one.

**Comment by TheGreatRambler** [comment]
Also, speaking of not very powerful, the only computer I have avaliable for the client is a computer running Windows Vista (32 bit), so you could say I don't care too much about performance because I don't have much better to use anyway.

**Comment by TheGreatRambler** [comment]
Okay, case closed. I have a working fork (it's very hacky, though, because I don't actually know Java!)
