### ISSUE TITLE
Reduce overhead caused by short renders

### ISSUE THREAD

**Issue by Saren-Arterius** [laurent-clouet/sheepit-client#170]
I am running sheepit on my workstation in hope of heating up my living room but there are currently a lot of short renders that finish under 20 seconds each frame. The short renders caused overhead and are wasting my hardware, and now my living room is still too cold. 

I know blocking such render projects is a way to reduce overhead, however I think there should be a way to improve the client's efficiency, such as requesting multiple jobs at the background. Any ideas?

**Comment by laurent-clouet** [comment]
The job can be rendered/downloaded while the previous job is uploaded BUT it's an option who is enabled/disabled by the server.
The goal of sheepit is to validate job, a lot of client are shutdown (by the user) unexpectedly so the less simultaneous operation are done, the better.

**Comment by JustAPerson** [comment]
I'd like to see this addressed as well. Right now (and almost all the time) my 15 minute loadavg is 75% CPU utilization due to short frames. I have a 64 thread cpu, and for short frames what often happens is most of the tiles (and threads) finish roughly at the same time but then a few stragglers will take ages to finish. This kills average CPU utilization. Ideally, sheepit would request multiple frames at once and once one frame begins to finish, start up the next one.

>The goal of sheepit is to validate job, a lot of client are shutdown (by the user) unexpectedly so the less simultaneous operation are done, the better.
Then only enable this behavior after the client has rendered many frames, as evidence that they will likely continue rendering far into the future.

**Comment by piegamesde** [comment]
What about allowing connections with >10h online time to pre-fetch the next job so they can start rendering while uploading the last one? That way we would get the best of both worlds
