### ISSUE TITLE
Add maximum runtime of render

### ISSUE THREAD

**Issue by krisives** [laurent-clouet/sheepit-client#46]
Some of my farmers are getting stuck somehow trying to render frames for 20+ hours. I don't see it until I wake up the next day usually. I run on Linux so I usually do this:

    ps -e | grep rend.exe
    10503 ?        22:47:40 rend.exe
    10531 ?        00:36:34 rend.exe
     ....

Then I kill the process manually. The problem with this method is:

* Lots of time is wasted until I kill the process
* After killing the job the farmer will wait 15 minutes to get back to work since it just thinks the render failed for some reason

My goal is to add a maximum execution limit on the client to limit this.

**Comment by laurent-clouet** [comment]
it's should be done on the server side, the server should detect that a render will take  a lot of time.
Few weeks ago i add some info on the keepmealive but i don't use it yet (it's on the todo list)

**Comment by laurent-clouet** [comment]
Today, I implemented a better keepmealive.
You should not have the behavior anymore, please let me know if you still have 20+ hours long render.

**Comment by krisives** [comment]
Nice work man.

**Comment by krisives** [comment]
Hi, does the client still allow for unlimited long job? I know you said you would make a server side fix, but why should the client not set it's policy? I have re-opened the issue.

**Comment by jejem** [comment]
IMHO the server should be able to drop clients which will take too long to render the frame, as it can be a blocking point to successfully render scenes. So the fact that the server enforce this is fine by me.

The fact that the client could ALSO do this, and not only the client, is okay too, but less important. It's distributed computing, the clients are supposed to be stupid slaves only doing what they are told, and stopping when they are told, and have the least decision-making possible.

As the client is open-source, you can fork/hack your own copy to enforce this feature if you want/need it, but honestly if it is not merged I will not complain.

Have a nice day!

**Comment by krisives** [comment]
> clients are supposed to be stupid slaves only doing what they are told

To a degree, except when it doesn't work - like right now these issues
cause a system configured for 6 cores to maintain an average of 4.01 over
an hour. I routinely check my logs and my loadavg and it's because it's
waiting 15 minutes in between various failures or stuck jobs. The client
needs to be smart enough to maintain a full work load.

> As the client is open-source, you can fork/hack your own copy to enforce
this feature if you want/need it, but honestly if it is not merged I will
not complain.

I don't think anyone cares enough that I should put any more effort into
it, and I have nothing to gain. Almost every time I've tried to do anything
with this project it's pushed off onto it's closed source server component.
I've moved all of my efforts into a 250 line script I wrote that does
everything the Java client does, and despite being hacked together and
quite simple keeps my machines at full utilization - something the Java
client routinely fails to do.

**Comment by jejem** [comment]
The fact that the server-side control of rendering duration may not work has nothing to do with the fact that the client doesn't support the feature. The first one is a bug and the latter is more of a feature request.

The 15 minute sleep in case of failure is too long for you? Well maybe it should be a config option then...

You have nothing to gain from providing a patch to an open-source client that you use, to have a feature that you want? Then don't do it, there is no obligation here... I understand your point of view about the feature/bug, but I really don't understand the way you try to fix thing, if you did your own 250 lines script because you don't want to provide a patch for the feature, why are you even talking about said feature? IMHO if you don't want to put an effort into this, don't try to reverse the thing by saying people don't care enough about it.

Have a nice day.

**Comment by krisives** [comment]
Problem solved for me, all I really care about right now. Best of luck with
your closed source server and pushing all the features into it.
