### ISSUE TITLE
Add job blacklist

### ISSUE THREAD

**Issue by krisives** [laurent-clouet/sheepit-client#47]
I'm going to add a way I can blacklist specific jobs. I've sent an e-mail using the contact form on the website but there are some jobs submitted that never advance or finish at all. They take up time doing something, then fail and force my farmer to wait 15 minutes. I usually get the same jobs the next day when I reboot my farmer.

**Comment by laurent-clouet** [comment]
It's not a good idea, it's should be done on the server side.

**Comment by laurent-clouet** [comment]
It's not a good idea, it's should be done on the server side because the client should not decide on what project to render..

At the moment, there is a blacklist on projects, if you failed to render a project you will not try to render it again ON YOUR SESSION. 
It means if you relaunch the client, you might be asked to render the broken project again.
It was made like this you could have a temporary issue on your computer (for example not enough memory). It is because at the time, we could not detect the type of failure (like out of memory, missing lib, out of harddrive,...) now we can so we could implement a persistant blacklist.

**Comment by krisives** [comment]
> It's not a good idea, it's should be done on the server side 

Well the source code for the server isn't available or something I have any control over. Also, while the server should certainly know about what is happening to perform scheduling, this is a client policy. The server-side scheduler should do a better job of detecting when the 20 minute policy is violated, but the client should be free to enforce the same policy.

> At the moment, there is a blacklist on projects, if you failed to render a project you will not try to render it again ON YOUR SESSION. 

I see, that explains why I only see the renders when I restart the farmers. Thank you for clarifying this.

> It means if you relaunch the client, you might be asked to render the broken project again.

That's fine I'm okay with it only using up time on restart. I was not aware of this feature already existing per-session.

**Comment by krisives** [comment]
Here is a thread about this happening to others:

https://github.com/laurent-clouet/sheepit-client/issues/47

It's not good that one bad render job can cause so much wasted render time.

**Comment by laurent-clouet** [comment]
I don't understand the message... #47 is this thread....

**Comment by krisives** [comment]
Not sure what happened that's supposed to be a link to the forums.
