### ISSUE TITLE
Raspberry Pi support

### ISSUE THREAD

**Issue by piegamesde** [laurent-clouet/sheepit-client#66]
I'd like to farm on my RPi B2 (with Raspbian). Starting the jar on it exits with "Error CPU not supported.". It turns out that Linux.java opens the file "/proc/cpuinfo" to find out about the CPU, but the lines "cpu family" and "model" don't exist in the file. So, haveData() in the CPU.java will return false, checkCPUisSupported() in Configuration.java too and the Client won't start running.

**Comment by laurent-clouet** [comment]
Hello,
I would love to use them but I don't think it's possible.
I have also an Raspberry b2 and i did some test on it.

It's not even remotely powerful, I did a test of a simple scene who render in 55s on my computer (intel i5-2500K a computer, i brought three years ago), the raspberry rendered it in 22min.
Furthermore the device only have 1GB (shared) of ram. Most of projects on sheepit are taking most than 1GB or ram so the raspberry can not handle it.

Anyway if you want to try, it's a working in progress patch.

(If you want to try, please use http://www-demo.sheepit-renderfarm.com i didn't add the armv7l blender on the main site)

**Comment by piegamesde** [comment]
Even if the RPi is not powerful, mine is always on, 24/7. The fact that it could render all the time would compensate its slowness. But if you say that it's not possible, I'll believe you. I'm not technical enough to add special hardware support. Instead, I will focus on the client itself.

**Comment by ChlorideCull** [comment]
I feel like support for armv6/armv7l would be great, despite the performance of the Raspberry Pi. I guess you could add a "slow mode" where for frames that slower computers work on, which would split that frame into a 10*10 grid, for better parallel working.

    tile_num_x = 0 #  0 to 9
    tile_num_y = 0 #  0 to 9
    bpy.context.scene.render.use_border = True
    bpy.context.scene.render.use_crop_to_border = True
    bpy.context.scene.render.border_min_x = 0.1 * tile_num_x
    bpy.context.scene.render.border_max_x = 0.1 * (tile_num_x + 1)
    bpy.context.scene.render.border_min_y = 0.1 * tile_num_y
    bpy.context.scene.render.border_max_y = 0.1 * (tile_num_y + 1)

This would output a tile you could use to stitch together entire frames server-side. The border_* coordinate floats are all between 0 and 1, so it's also resolution independent.

**Comment by ChlorideCull** [comment]
(come to think to it, such a "slow mode" would be great for single-frame renders, where you have a single, long frame)

**Comment by bokanist** [comment]
No that's definitely not worth the efforts. It's like building render farm out of obsolete computers. They do not offer enough perf/watt to compete with modern hardware.

**Comment by AGSPhoenix** [comment]
I agree with @bokanist. Modern ARM devices just don't have enough power to be worth the development effort. And I don't just mean on a per-processor basis; the userbase of ARM devices is a lot smaller than x64, so the total increase of the farm's performance would be incredibly small.

I'm not saying it shouldn't be implemented, just that it seems like a waste of time.

**Comment by principat** [comment]
I do not agree. The number of ARM devices is growing each day. Handys, mini pc like raspberry, tablets, most of these "mobile" devices are based on ARM. And why shouldn't they be used for rendering.

**Comment by supersammy7000** [comment]
I think something like a Raspberry Pi is too slow for support to be added just for it but I do think some of the more powerful ARM devices should be supported and if those are you might as well add Raspberry Pi support.

**Comment by AGSPhoenix** [comment]
@principat While true, it's more complicated than that. There are over a billion ARM devices out there, and probably 2-100 million with interesting specs, but how many of those are owned by people who would be willing to donate their computing power? And of those, how many would want go with SheepIt over one of the BOINC projects? I don't think that's a large number.

And those ARM devices just don't have a lot of performance. Based on the numbers in [this](http://www.computingcompendium.com/p/arm-vs-intel-benchmarks.html) page of benchmark results, one of the best ARM processors, the Nvidia Tegra 4, struggles to keep up with midrange laptop processors. And the 4770k blows it out of the water with almost 6x the performance.

Now I am making a lot of assumptions about the number and performance of the ARM clients we'd get, but I do think they're reasonable approximations, and the picture they paint isn't that inspiring in my opinion. If you just think it'd be cool to run your own ARM stuff on the farm, that's totally fine, but looking at the big picture in terms of added render performance of the farm as a whole, I just don't think it's worth the effort.

With that said, if you put in a pull request with everything all ready to go, and you have some hardware that isn't just going to end up on the very_slow_computer scheduler and bog down jobs by taking ages to render that one last frame of a project, then I'd say go ahead. However, someone (Laurent?) will need to consider what to do when people start trying to render with low-end devices that would struggle to compete with a 5 year old netbook.

**Comment by ekaj2** [comment]
I would like to mention that while a raspberry pi doesn't have the power to render most scenes, I have some low poly art and grease pencil projects that they could tackle quite easily. The magic with a cheap computer like that is that there could very easily be one or two thousand of them that could take out the frames that could be rendered in a few seconds on a faster computer.

---

Let's do a bit of math (with some major estimates)...

Given a 10,000 frame animation (~ 10 minutes), rendering in 1 second on a PC, and the ratio given by Laurent (of 55 seconds to 22 minutes on a Pi)...lets say the Pi was $35 and the PC was $750.

1. The Pi is ~4% of the speed of the PC (according to Laurent's ratio).
2. For the price of the PC, you can get just over 20 RPis.
3. As was mentioned, the Pi would be on 24/7, while PCs are mostly running at night after we are done working (maybe 8 hrs.) and probably not every day of the week (lets say 6).

---

### $750 worth of PC's:
*1 computers x 100% speed x 8 hrs. x 6 days = 48 hypothetical rendering power units (RPUs)*

### $750 worth of Raspberry Pi's:
*20 computers x 4% speed x 24 hrs. x 7 days = 134 RPUs*

---

When you look at it this way, the Pi carries a bit more weight, doesn't it?

**Comment by SebastienCaunes** [comment]
This thread is really not worth spending time on.

In render farm considerations, processing power doesn't add like apples. Each node must provide a minimum processing power, otherwise it would slow down the whole process. Sure it would be better if we could split the rendering of a frame in smaller tasks, but even then it will waste the bandwith of the main file server. Sending the project data to a raspberry that will compute at some  %  of the speed of a regular computer.

Laurent time is precious,  like any other developer involved in the project. This time will be much more productive spent on other tasks.

It's interesting to draw a graph of power/price ratio, you'll see that both extremes are not interesting. On high end device you spend double the price to get 10% speed increase.

@ekaj2 : Why do you compare a PC running 8 hours during 6 days with 20 raspberries running 24/7 ? People farming credits on sheepit let their computer run 24/7. Not to mention, the boxes for 20 RSPI, 20 power adapters, plugs, the sd cards, the setup and maintenance effort, the ethernet cables, the switch, the bandwidth usage... What a mess ! And this PC was just a small CPU, try to compare with a dual GPU :) .

**Comment by ekaj2** [comment]
@SebastienCaunes I realize that I used numbers that favored the Pi, but like I said they are just estimates. My point is just that if the Pi's only get small frames, and there were enough of them, they could feasibly be a help. I understand your points, and they are certainly valid, but I wanted to mention that the Pi's power is in numbers (due to the lower cost). If ever possible in the future, I think it isn't a bad idea, but I agree with you that the dev time is more important in other areas (for now at least).

BTW, I don't have a Raspberry Pi...

**Comment by SebastienCaunes** [comment]
I have some raspberries. They are tiny computer with a big graphic card full of hardware acceleration, it makes them quite good for media center. That's why people think they are powerfull. But their I/O and raw power is very low... I also forgot that if you make them run at 100% for long time you'll need to cool them down if you don't want them to burn your house.

If we use raspberries for rendering, then why not DSL boxes, phones, tablets...

**Comment by TheGreatRambler** [comment]
I have a working fork for the raspberry pi (and other ARM architectures). It can be found [here](https://github.com/TheGreatRambler/sheepit-client).

**Comment by TheGreatRambler** [comment]
I officially have a [working fork](https://github.com/TheGreatRambler/sheepit-client). File issues on the fork if you find problems.

**Comment by piegamesde** [comment]
Thank you. I'll try it out later.

**Comment by IceHacks** [comment]
You might aswell be using a piano to render your images.
