### ISSUE TITLE
[RequestFromUser] Add an option to set alternate memory limits.

### ISSUE THREAD

**Issue by laurent-clouet** [laurent-clouet/sheepit-client#72]
For example, I know that I need for myself 6 of the 16GB of my computer, so I can set "-memory 10", and not get a 15GB project that will make my computer swap. 
On the graphical ui, a slider like the one cpu will be great.

(sheepit feature id 1371731902)

**Comment by BloodyRain2k** [comment]
What'd also be nice is if the client would soft blacklist such projects if they were crashing due to needing too much memory. I have that sometimes that half the projects I get crash because the thing runs out of memory, sometimes even crashing half the system in the process.
Maybe also allow the memory control over the site's profile where you can just select your known machines and set it from there, though as commandline it'd work too. Just throwing ideas here.

**Comment by principat** [comment]
this is addressed at PR #105

**Comment by laurent-clouet** [comment]
merged in master
