### ISSUE TITLE
[RequestFromUser] Add an option to specify the size of tiles for the render

### ISSUE THREAD

**Issue by laurent-clouet** [laurent-clouet/sheepit-client#73]
Add an option to specify the size of tiles for the render (with that feature we can adjust tiles size for GPU or for CPU, because actually the projects use small tiles for CPU, and with GPU it's very longer than big tiles !). 
And possibly an info of the size of the frame rendered, to adjust tiles size more effectively.	

**From Sheepit's owner**, right now there is 3 sizes:
* 16x16 for CPU
* 128x128 for GPU under 1GB of vram
* 256x256 for GPU over 1GB of vram
an "advanced option" could be nice, most like the owner of the gpu knows what is the best tile size.

(feature id: 1371731749)

**Comment by JacksonML** [comment]
I think it would be better to use the auto tile size addon instead. The best tile size mostly depends on the size of the image. For example, setting the tile size to 8x8 on GPU as we know will make it render horribly slow in most cases, and there won't be much telling on what the owner thinks might be the best tile size, or if people maliciously try to get more credits by rendering at a slower pace.

**Comment by laurent-clouet** [comment]
You can't use python (i.e. addon) for security reason.

**Comment by JacksonML** [comment]
Where do you get your blender download from? The default install of blender has the addon installed.

**Comment by piegamesde** [comment]
"If people maliciously try to get more credits by rendering at a slower pace"
I don't think someone intelligent would do this, because he would lose credits instead of getting more. The reason is the bonus you get for every frame independent of the rendered time, which makes fast renders more attractive.
If I render 2 frames in 30 min, I get (14 + 7 * 15) * 2 = 238 credits. One frame in the same time: 14 + 7*30 = 224. Ten rendered frames in half an hour: (14 + 7 * 3) * 10 = 350.
