### ISSUE TITLE
Proposal: Use bittorrent protocol to distribute project files among renderers

### ISSUE THREAD

**Issue by marioestrella** [laurent-clouet/sheepit-client#76]
I haven't dug very deep into the code yet, but from using the client it seems like the projects are downloaded directly from the server once.

I propose using the bittorrent protocol in order to retrieve files from the server. 
- Have the client then run a background process sharing the project files in addition to rendering.  If the client contains the project file in it's cache it can also send pieces of the file to other new connecting clients that are assigned that job.  
- Once a project is completed the server can send a delete command to all the clients to ensure that  project is removed and no longer shared via the bittorrent protocol.

This should in allow for larger projects to be rendered as well without stressing the server.  Instead of 200 clients attempting to download a 2GB file you really only need a few to actually download the file and then it should be distributed among the workers.

**Comment by piegamesde** [comment]
That's a good idea. Someone should pick up one of these [https://github.com/search?utf8=%E2%9C%93&q=java+torrent](url) and implement it into the client. Some additional points: 

- Locally available projects should be priorized to remote ones
- The client should take care of having downloaded projects in spare to minimize the time its waiting for downloading projects

**Comment by ChlorideCull** [comment]
If such is to be implemented, you should be able to place appropriate limits.

I think that the current maximum size of 500 MB is not just to limit storage use on the server, but also to limit usage on clients. Such a project size is already fairly large for what is essentially charity work, and even bigger would kill users on metered connections.

Not to mention how some ISPs treat BitTorrent connections.

**Comment by laurent-clouet** [comment]
ChlorideCull is raising the points i was thinking of. You can not really use bittorrent because it's not available everywhere.

An another reason is the number of user/renderer, right now there is between 150 and 200 renderers at the same, i don't think it a big enough number of using torrent because their upload brandwith is not really good.

**Comment by forneuszagan** [comment]
Very good points!

I agree that moving over to BitTorrent completely would be foolish, as not everyone even updates the client.  A better idea would be to have BitTorrent as an addition to the current download process in order to reduce bandwidth constraints and take advantage of the distributed nature of Sheep It that's already in place.

- Those that cannot use BitTorrent for whatever reason will continue to use HTTPS a check would just need to be made during the same time you do the computer check to see if they can do this. 

- Have the server always act as a seed, not just a tracker

- In regards to the 150-200 renderers this can vary greatly depending on their location.  The best way to get an accurate value of their upload strength is to see how long it takes them to upload a rendered image to the server, that should give you a good estimate as to what the strength is.

**Comment by piegamesde** [comment]
One improvement that still could be done is to download the next project while rendering. Optimal would be a pool of several downloaded projects at any time to minimize idle time between renders. This should be an optional feature for those with bad internet

**Comment by bokanist** [comment]
Do you know https://syncthing.net/ ?
It's a peer to peer folder synchronisation tool.
May be a solution.
But I don't think this feature is a priority.

Once sheepit will reach a critical size, the file server may become the bottleneck. Maybe at this time the project will generate enough revenue to afford strongers servers.

**Comment by stuarta0** [comment]
I agree with adding this feature. Bittorrent protocol can be implemented without using the Bittorrent Inc client. I'm sure there's already code floating around that implements it, but I'm not a Java dev so I wouldn't know. See http://www.bittorrent.org

On a local network with multiple nodes it would also save my internet connection since the fastest peers would be local.

AFAIK the server code isn't public so I won't presume to know how you've set it up but if I were investigating it I'd be looking at Amazon's S3 bittorrent capabilities.

**Comment by ChlorideCull** [comment]
These days webseeds should be well supported by libraries (special section in the torrent details HTTP URLs where files can also be sourced from), so if implemented, actual participation in sending/receiving torrent data could be made opt-in without having to maintain two methods of download.

The best bittorrent library I know of is [libtorrent](http://www.libtorrent.org/) (not lib**T**orrent), and you should be able to make it not participate in a DHT by not seeding it on initialization. This assumes you won't be running a tracker, but rely on DHT.

**Comment by Moredread** [comment]
I don't think that syncthing will be easy to integrate, as there is no alternative implementation that is suitable as a library at the moment as far as I know.

**Comment by alset333** [comment]
Hey, is there anyone who's looked into this any more? In case anyone sees this and wants to code, I'd like to mention one issue with Torrents is they make it more likely to reveal IPs of other users. Not sure if this is really a problem, but if you wanted someone could use something along the lines of [OnionShare](https://github.com/micahflee/onionshare), which uses the TOR network for (slower) anonymous file transfers.
You could arrange the transfers through the website, but actually run the download from client-to-client. It really depends how many MB you're transferring though, as the TOR network will take a long time to transfer large files.
Not sure how easy it would be to implement compared to BitTorrent though.

Good luck to anyone who might still be working on any of this BitTorrent/P2P/TOR stuff!

**Comment by laurent-clouet** [comment]
I will NOT happen.
I'm only keeping the thread open to let people know.

Even if i were willing to change the protocol, soon i say the words "peer to peer" or even "torrent", sheepit will lose access to most of professional network. Only http(s) is allow everywhere.

**Comment by alset333** [comment]
Understandable. Thanks for a quick reply!
