### ISSUE TITLE
Handling of bad projects

### ISSUE THREAD

**Issue by bokanist** [laurent-clouet/sheepit-client#80]
There is currently a project called Render_Test_Day_Jatniel that is blocking both of my computers.
I clicked on block project, but it came back on one computer.

Maybe the image is very long to render. But I leave it several hours without success.

How is this handled by the system ?

**Comment by laurent-clouet** [comment]
If you click on block project it will only block it on your session.
If a lot of people block the project (~40 times call of block) or it's be detecting as taking too long (every ~15min the client send the remaining render time) them the project will be blocked for everyone.
Some client have to be a guinea pig on a project because there is no away to know if the project will be too heavy. There is a static detection but it's only for really heavy project (and it cannot detect the memory used) (https://www.sheepit-renderfarm.com/news.php?id=1457440382 )

I'm closing the issue, It's not a client issue.

**Comment by bokanist** [comment]
Right, thank you for your answer.
