### ISSUE TITLE
Project not being blocked

### ISSUE THREAD

**Issue by supersammy7000** [laurent-clouet/sheepit-client#90]
I'm running the SheepIt client and I keep getting the "espresso maker" project and it takes hours to render so I try to block it but it keeps coming back. It is only this one project.

**Comment by supersammy7000** [comment]
I just got the same problem again with "logo sesto senso-pre3D". I just let it render because it is only like ~20 minutes it says but it give the error "RENDERER_OUT_OF_ MEMORY" when completed. If I keep blocking it it will just say no jobs available.

**Comment by BloodyRain2k** [comment]
That senso project ended for me the same way, first wasting tons of time on my hardware only to get to "RENDERER_OUT_OF_ MEMORY" on completion.
And I don't even got that bad hardware, sure 2x GTX 970 and 32gb aren't THAT impressive but I think it still shows that some projects go overkill, and when they keep coming back and just waste your time it's annoying.
I don't even know what ran out of memory, my physical memory was it definitely not, that didn't even come close to 50% being used, and the GPU wasn't it either or it'd had been a CUDA error instead, so I'm wondering.

Anyways, in cases like these I wish the server would get that told and blacklist these projects on it's own for like a week for the machine in question because it's unlikely to work the next time <_<
And have a little list in the user area where these are listed and can manually be unblocked if you for example changed your hardware (though since the server knows this also it could also do that on it's own).

I know that there's temporary blocking for the session but that doesn't seem to work since I've got that project, had it fail, say that there are no jobs available, and after a while was it back again anyways, and of course failed again.
The temp blocking, if it works, is kinda useless to me anyways since I'm running the client with an own program when my screensaver turns on so I have a lot of sessions happening per day making a per-session temp block very pointless.

And a question on the side, how does one block a project with the client ran in console mode (-ui text) ?
And is it perhaps possible to send a list of blocked projects manually? (I bet not but asking won't hurt)

**Comment by principat** [comment]
with pr #101 you can block a project at command line
with pr #104 you can set a max. rendertime for a project

**Comment by principat** [comment]
#107 block project by time and memory

**Comment by luguina** [comment]
#211 block current frame/current project permanently for current client instance.
