### ISSUE TITLE
Not enough memory - which cannot be true

### ISSUE THREAD

**Issue by schtibe** [laurent-clouet/sheepit-client#91]
I get the error message 

> Error Renderer has crashed. It's usually due to a bad project or not enough memory. There is nothing you can do about it. Will try another project in a few minutes.
> Requesting Job
> 

Which is ... almost impossible, since I definitely have enough memory. Check this screenshot:
http://pasteall.org/pic/show.php?id=106541

Maybe there's another error? Is it possible to see the reason for the crash?

**Comment by laurent-clouet** [comment]
Can you give me your sheepit login so i can check if i have any more log.

**Comment by schtibe** [comment]
It is arsenbonbon

On 8 September 2016 16:46:12 CEST, Laurent Clouet <notifications@github.com> wrote:
>Can you give me your sheepit login so i can check if i have any more
>log.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/laurent-clouet/sheepit-client/issues/91#issuecomment-245621749

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by laurent-clouet** [comment]
You can add --verbose to check yourself.
But on the server side i have this:
08-09 16:43:24 (debug) GUI Rendering project "computer_check"
08-09 16:43:24 (debug) [/tmp/farm_1358490921496677504/c36db40aa5e59f5ea4ff139180353dbc/rend.exe, --factory-startup, --disable-autoexec, -b, /tmp/farm_1358490921496677504/fed2b5d02774c785d31c121a7c9ae217/compute-method.blend, -P, /tmp/farm_1358490921496677504/script_2969438205642417417, -o, /tmp/farm_1358490921496677504/1_, -f, 0340, -x, 1]
08-09 16:43:24 (debug) renderer output
08-09 16:43:24 (debug) found bundled python: /tmp/farm_1358490921496677504/c36db40aa5e59f5ea4ff139180353dbc/2.77/python
08-09 16:43:24 (debug) read blend: /tmp/farm_1358490921496677504/fed2b5d02774c785d31c121a7c9ae217/compute-method.blend
08-09 16:43:24 (debug) Writing: /tmp/farm_1358490921496677504/compute-method.crash.txt
08-09 16:43:24 (debug) end of rendering
08-09 16:43:24 (error) Client::runRenderer no picture file found (after finished render (filename_without_extension 1_0340)
08-09 16:43:24 (error) Client::runRenderer crash file found => the renderer crashed
08-09 16:43:24 (error) Client::work problem with runRenderer (ret RENDERER_CRASHED)
08-09 16:43:24 (error) Error Renderer has crashed. It's usually due to a bad project or not enough memory. There is nothing you can do about it. Will try another project in a few minutes.
08-09 16:43:24 (debug) Sending error to server (type: RENDERER_CRASHED)

"computer_check" project is the project to check if your machine can render a frame, this frame is always the first frame of your session. If you can't render it, you can't participate.
If you are curious about the project : https://www.sheepit-renderfarm.com/computer_check.zip

**Comment by schtibe** [comment]
Thank you! Blender is actually segfaulting on this system, I'll have to check why.

**Comment by schtibe** [comment]
Just for your information: it was a driver problem with my nvidia hardware. I didn't notice because I usually don't run blender on this computer.
